name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release-docker:
    uses: ./.github/workflows/sztp.yaml
    secrets: inherit
  release-binaries:
    uses: ./.github/workflows/binaries.yaml
    secrets: inherit
